### ISSUE TITLE
UI in tools screen - outOfMeomoryError

### ISSUE THREAD

**Issue by arstagaev** [arstagaev/spx#1]
```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 37748748 byte allocation with 16777216 free bytes and 22MB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.BitmapFactory.nativeDecodeAsset(BitmapFactory.java)
       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:620)
       at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:455)
       at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1155)
       at android.content.res.ResourcesImpl.createFromResourceStream(ResourcesImpl.java:1414)
       at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:790)
       at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:632)
       at android.content.res.Resources.getDrawable(Resources.java:804)
       at android.content.Context.getDrawable(Context.java:525)
       at androidx.core.content.ContextCompat$Api21Impl.getDrawable(ContextCompat.java:862)
       at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:480)
       at com.revolve44.solarpanelx.ui.fragments.ToolsManagerFragment.initRecyclerViewWithMapAndNums(ToolsManagerFragment.kt:58)
       at com.revolve44.solarpanelx.ui.fragments.ToolsManagerFragment.access$initRecyclerViewWithMapAndNums(ToolsManagerFragment.kt:27)
       at com.revolve44.solarpanelx.ui.fragments.ToolsManagerFragment$onViewCreated$2.invokeSuspend(ToolsManagerFragment.kt:43)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6242)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)

```

**Comment by arstagaev** [comment]
Same problem tools manager ```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 37748748 byte allocation with 16777216 free bytes and 22MB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.BitmapFactory.nativeDecodeAsset(BitmapFactory.java)
       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:620)
       at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:455)
       at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1155)
       at android.content.res.ResourcesImpl.createFromResourceStream(ResourcesImpl.java:1414)
       at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:790)
       at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:632)
       at android.content.res.Resources.getDrawable(Resources.java:804)
       at android.content.Context.getDrawable(Context.java:525)
       at androidx.core.content.ContextCompat$Api21Impl.getDrawable(ContextCompat.java:862)
       at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:480)
       at com.revolve44.solarpanelx.ui.fragments.ToolsManagerFragment.initRecyclerViewWithMapAndNums(ToolsManagerFragment.kt:58)
       at com.revolve44.solarpanelx.ui.fragments.ToolsManagerFragment.access$initRecyclerViewWithMapAndNums(ToolsManagerFragment.kt:27)
       at com.revolve44.solarpanelx.ui.fragments.ToolsManagerFragment$onViewCreated$2.invokeSuspend(ToolsManagerFragment.kt:43)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6242)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)
```
